# Generated by Django 5.2.4 on 2025-08-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_employee_email_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
